defmodule Aoc25.Day07Test do
  use ExUnit.Case, async: true

  alias Aoc25.Day07
  doctest Day07

  setup do
    example =
      """
      .......S.......
      ...............
      .......^.......
      ...............
      ......^.^......
      ...............
      .....^.^.^.....
      ...............
      ....^.^...^....
      ...............
      ...^.^...^.^...
      ...............
      ..^...^.....^..
      ...............
      .^.^.^.^.^...^.
      ...............
      """

    {:ok, example: example}
  end

  describe "part 1" do
    test "part 1", ctx do
      assert Day07.part1(ctx.example) == 21
    end
  end

  describe "part 2" do
    @tag skip: "pending"
    test "part 2", ctx do
      assert Day07.part2(ctx.example) == -67
    end
  end
end
